name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.15.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # Add the following steps for migrate undo, migrate, and seed
    - name: Set up database
      run: npm install knex -g
    - name: Migrate Undo
      run: knex migrate:undo --all --env production
    - name: Migrate
      run: knex migrate:latest --env production
    - name: Seed
      run: knex seed:run --env production
